project_name: curl-httpie
builds:
-
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - freebsd
  - windows
  binary: http
git:
  short_hash: true
brew:
  github:
    owner: rs
    name: homebrew-tap
  commit_author:
    name: Olivier Poitrey
    email: rs@rhapsodyk.net
  homepage: https://github.com/rs/curl-httpie
  description: HTTPie for curl
  conflicts:
  - httpie

release:
  name_template: "{{.ProjectName}}-v{{.Version}}"
